-- 1. Core Player Data
CREATE TABLE PLAYERS (
    PLAYER_ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    CURRENCY_BALANCE NUMBER(19,4) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Base Catalog (What an item is conceptually)
CREATE TABLE ITEM_DEFINITIONS (
    DEF_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ITEM_NAME VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(20) NOT NULL CHECK (CATEGORY IN ('WEAPON_SKIN', 'STICKER', 'CHARM', 'CASE')),
    RARITY VARCHAR2(20) NOT NULL,
    BASE_PRICE NUMBER(19,4) -- Used as a reference for starting bids
);

-- 3. Player Inventory (The unique, physical instance)
CREATE TABLE INVENTORY_ITEMS (
    INSTANCE_ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    PLAYER_ID RAW(16) REFERENCES PLAYERS(PLAYER_ID),
    DEF_ID NUMBER REFERENCES ITEM_DEFINITIONS(DEF_ID),
    WEAR_FLOAT NUMBER(8,7), -- E.g., 0.014523 (Factory New)
    IS_TRADE_LOCKED NUMBER(1) DEFAULT 0,
    ACQUIRED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Customization Mapping (Attaching stickers/charms to a skin)
CREATE TABLE APPLIED_CUSTOMIZATIONS (
    MAPPING_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SKIN_INSTANCE_ID RAW(16) REFERENCES INVENTORY_ITEMS(INSTANCE_ID),
    CUSTOMIZATION_DEF_ID NUMBER REFERENCES ITEM_DEFINITIONS(DEF_ID),
    SLOT_INDEX NUMBER(1) NOT NULL CHECK (SLOT_INDEX BETWEEN 1 AND 4)
);

-- 5. The Order Book (For Limit Orders and Swing Trading)
CREATE TABLE MARKET_ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAYER_ID RAW(16) REFERENCES PLAYERS(PLAYER_ID),
    ORDER_TYPE VARCHAR2(10) NOT NULL CHECK (ORDER_TYPE IN ('BUY', 'SELL')),
    -- If SELL, which specific instance are they selling?
    INSTANCE_ID RAW(16) REFERENCES INVENTORY_ITEMS(INSTANCE_ID) NULL,
    -- If BUY, what type of item are they bidding on?
    DEF_ID NUMBER REFERENCES ITEM_DEFINITIONS(DEF_ID) NULL,
    TARGET_PRICE NUMBER(19,4) NOT NULL,
    STATUS VARCHAR2(15) DEFAULT 'OPEN' CHECK (STATUS IN ('OPEN', 'FILLED', 'CANCELLED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Time-Series Execution Log (For generating Price Action charts)
CREATE TABLE MARKET_TRANSACTIONS (
    TX_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BUYER_ID RAW(16) REFERENCES PLAYERS(PLAYER_ID),
    SELLER_ID RAW(16) REFERENCES PLAYERS(PLAYER_ID),
    INSTANCE_ID RAW(16) REFERENCES INVENTORY_ITEMS(INSTANCE_ID),
    EXECUTION_PRICE NUMBER(19,4) NOT NULL,
    EXECUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
